// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerEffectiveCapabilities } from "./ControllerEffectiveCapabilities";
import type { ControllerLease } from "./ControllerLease";

export type ControllerSession = { sessionId: string, mainThreadId: string, activeLease: ControllerLease | null, authorizationEpoch: bigint, sessionSequence: bigint, effectiveCapabilities: ControllerEffectiveCapabilities, leaseExpiresInMs: bigint | null, authorizationExpiresInMs: bigint | null, };
