// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControllerEffectiveCapabilities = { readMainThread: boolean, subscribeMainThread: boolean, acquireControl: boolean, releaseControl: boolean, mutateMainThread: boolean, answerPrompts: boolean, };
