// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerControlOwnershipChangedReason } from "./ControllerControlOwnershipChangedReason";
import type { ControllerLease } from "./ControllerLease";

export type ControllerControlOwnershipChangedNotification = { sessionId: string, mainThreadId: string, reason: ControllerControlOwnershipChangedReason, authorizationEpoch: bigint, ownerEpoch: bigint, sessionSequence: bigint, activeLease: ControllerLease | null, };
