// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadReadResponse = { thread: Thread,
/**
 * Monotonic app-server sequence number for the latest live event known for
 * this thread when the snapshot was built.
 */
lastSequence: bigint, };
